name: LinkCheck

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: master
      - name: Install dependencies
        run: sudo pip3 install pyyaml
      - name: Check all links
        run: |
          sudo python3 tests/gen-links.py
          sudo bash tests/linkcheck.sh

